Add SN2 Reaction Simulation
virtual-labs/exp-sn2-reaction-iiith pull request #3
Opened 2021-08-05 22:35 UTC by b30wulffz

2021-08-09 05:04 UTC, raj-vlabs requested changes
1. Aim has multiple grammatical and spelling mistakes. Please run through a grammar validator.
2. Theory also needs to be reformatted and verified.
3. Looking at the simulation, I do not have any clue what I am supposed to do, esp with the input and output buttons on each item.
4. I am not clear why we are copying over ChemDoodleWeb files instead of linking with them. Copying means caching will not take effect.

2021-08-09 05:04 UTC, raj-vlabs commented on experiment/aim.md
> +When two (especially organic) molecules approach each other, there is a possibility of several different chemical reactions between them; each giving different products. Many reactions occur in a sin
Multiple grammatical issues here:
1. 'collide with sufficient energy' in place of 'collide with a suffucient energy'.
2. Sufficient is also misspelled in the last line.
3. 'many reactions do not occur in a single step but follow multi-steps' in place of 'many reactions do not occur in a single step but follows multi-steps'.
4. Please run it through a grammar checker, too many to list.

2021-08-09 05:04 UTC, raj-vlabs commented on experiment/experiment-name.md
> +## Transition State Calculation for a SN2 reaction
Do we need 'a' before SN2 here?

2021-08-09 05:04 UTC, raj-vlabs commented on experiment/procedure.md
> +4. Use mouse to interact with molecule, by rotating, and zooming around it.
Mouse will not be present on touch devices.

2021-08-09 05:04 UTC, raj-vlabs commented on experiment/simulation/.vscode/settings.json
> +{
Please exclude this file from the repo.

2021-08-09 05:04 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +const transitionstate =
Please use camelCase naming for js variables and functions.

2021-08-19 11:40 UTC, raj-vlabs requested changes
1. There are a few errors on the simulation page, which should have been verified before submitting for the review. They are probably coming because the path to load ChemDoodleWeb has not been updated.
2. From the experiment it's still not clear what the user is supposed to do with the input and output buttons. This needs to be confirmed with Priya
3. On phone resolution, the input and output buttons start overlapping.

2021-08-19 11:40 UTC, raj-vlabs commented on experiment/posttest.json
> +      "question": "Which statement is true about S N 2 mechanism?",
There's gap between S N 2 at a few places in this file

2021-08-19 11:40 UTC, raj-vlabs commented on experiment/simulation/index.html
> +      src="chemdoodleWeb-9.2.0/ChemDoodleWeb.js"
Path needs to be updated to load it from the cdn.

2021-08-19 17:12 UTC, b30wulffz commented
> 1. There are a few errors on the simulation page, which should have been verified before submitting for the review. They are probably coming because the path to load ChemDoodleWeb has not been updated.
> 2. From the experiment it's still not clear what the user is supposed to do with the input and output buttons. This needs to be confirmed with Priya
> 3. On phone resolution, the input and output buttons start overlapping.

Resolved

2021-08-19 17:45 UTC, raj-vlabs approved these changes

2021-08-19 17:46 UTC, merged